import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import WithLayout from "./components/WithLayout";
import { UserProvider } from "./context/UserContext";
import { Suspense } from "react";
import Loading from "./loading";
import { SocketProvider } from "./context/socket";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-right" />
        <SocketProvider>
          <UserProvider>
            <Suspense fallback={<Loading />}>
              <WithLayout children={children} />
            </Suspense>
          </UserProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
